name: Development push

on:
  push:
    branches:
      - development

jobs:
  quality:
    name: Quality
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup latest Deno version
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Run Deno fmt
        run: deno fmt --check **/*.ts

      - name: Run Deno lint
        run: deno lint **/*.ts